### ISSUE TITLE
Des int ne serait pas mieux que des char pour _width et _height dans Room ?

### ISSUE THREAD

**Issue by mylainos** [chaipokoi/unamedRogueLike#2]
``` c++
struct Room
{
    unsigned int _x;
    unsigned int _y;
    unsigned char _width;
    unsigned char _height;
    bool _connected;
    std::vector<int> _neibhours;
};
```

Je pense que ça pose même des problèmes ici:

``` c++
rooms[i]._width = rand() % ROOM_WIDTH_MAX + 5;
rooms[i]._height = rand() % ROOM_HEIGHT_MAX + 5;
```

avec -Wall j'ai ces erreurs:

```
Dungeon.cpp:28:48: attention : statement has no effect [-Wunused-value]
   rooms[i]._width = rand() % ROOM_WIDTH_MAX + 5;
                                                ^
Dungeon.cpp:29:50: attention : statement has no effect [-Wunused-value]
   rooms[i]._height = rand() % ROOM_HEIGHT_MAX + 5;
                                                  ^
```

**Comment by Cl0v1s** [comment]
Nop, on gagne énormément en place:
On fait jamais des salles de plus de 20 de largeur, soit meme pas 5 bits pourquoi en utiliser 32 ?

-----Message d'origine-----
De : "Hugo Thiessard" notifications@github.com
Envoyé : ‎20/‎09/‎2015 04:07
À : "chaipokoi/unamedRogueLike" unamedRogueLike@noreply.github.com
Objet : [unamedRogueLike] Des int ne serait pas mieux que des char pour_width et _height dans Room ? (#2)

**Comment by mylainos** [comment]
Oui mais les salles ne sont utilisés qu'à la génération du donjon. Ça veux dire quoi les erreurs d’après toi ?

**Comment by Cl0v1s** [comment]
Tu parles de quelles erreurs ? :)

**Comment by mylainos** [comment]
`statement has no effect`

**Comment by Mylainos** [comment]
```statement has no effect```chaipokoi/unamedRogueLike a écrit :Tu parles de quelles erreurs ? :)

**Comment by Mylainos** [comment]
J'arrive pas à envoyer bien...chaipokoi/unamedRogueLike a écrit :Tu parles de quelles erreurs ? :)

**Comment by Cl0v1s** [comment]
Je n'ai pas d'erreur statement has no effect :/

**Comment by mylainos** [comment]
Ajoute `-g -Wall` à ton compilo

**Comment by Cl0v1s** [comment]
Je compile avec Visual c++.  
Et je suis déjà en warning All.  
Peut être qu'il y a un porblème de priorité de calcul, genre il attend un truc sur 8 bits, sauf que rand() sort sur du 32 donc le compilo s'affole avant de faire le modulo. 

Faut essayer de soit:
- Mettre des parenthèses
- faire passer le rand+modulo dans un entier 32 bits avant de le caser dans un char.
- Faire comme tu dit et mettre des int puisque de toutes façons on delete les rooms à la fin de la génération.

D'ailleurs de toute façon y'a une erreur, le code juste serait ici:

``` c++
rooms[i]._width = rand() % (ROOM_WIDTH_MAX-5) + 5;
rooms[i]._height = rand() % (ROOM_HEIGHT_MAX-5) + 5;
```

Donc teste en mettant des int voir, parce que chez moi j'ai pas d'erreur :)

**Comment by Cl0v1s** [comment]
D'ailleurs ton code n'était pas à jour, le -5 était dans mes derniers commit j'avais pas du push :)
